import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import thaiFont from "../assets/fonts/THSarabunNew.ttf";

const formatCurrency = (num = 0) =>
  Number(num).toLocaleString("th-TH", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });

async function loadThaiFont(doc) {

  const res = await fetch(thaiFont);
  const buffer = await res.arrayBuffer();

  const base64 = btoa(
    new Uint8Array(buffer).reduce(
      (data, byte) => data + String.fromCharCode(byte),
      ""
    )
  );

  doc.addFileToVFS("THSarabunNew.ttf", base64);
  doc.addFont("THSarabunNew.ttf", "THSarabunNew", "normal");

}

function calculateTaxBreakdown(income) {

  const brackets = [
    { limit: 150000, rate: 0 },
    { limit: 300000, rate: 0.05 },
    { limit: 500000, rate: 0.1 },
    { limit: 750000, rate: 0.15 },
    { limit: 1000000, rate: 0.2 },
    { limit: 2000000, rate: 0.25 },
    { limit: 5000000, rate: 0.3 },
    { limit: Infinity, rate: 0.35 },
  ];

  let previous = 0;
  let remaining = income;

  const result = [];

  for (let b of brackets) {

    if (remaining <= 0) break;

    const taxable = Math.min(b.limit - previous, remaining);

    const tax = taxable * b.rate;

    result.push([
      `${previous.toLocaleString("th-TH")} - ${
        b.limit === Infinity ? "ขึ้นไป" : b.limit.toLocaleString("th-TH")
      }`,
      `${b.rate * 100}%`,
      `${formatCurrency(tax)} บาท`,
    ]);

    remaining -= taxable;
    previous = b.limit;

  }

  return result;

}

export default async function generateTaxPDF({
  summary,
  transactions = [],
  deductions = [],
}) {

  const doc = new jsPDF();

  await loadThaiFont(doc);

  doc.setFont("THSarabunNew", "normal");

  const pageWidth = doc.internal.pageSize.width;

  // HEADER

  doc.setFontSize(24);
  doc.text("TaxBuddy", pageWidth / 2, 18, { align: "center" });

  doc.setFontSize(18);
  doc.text("รายงานการคำนวณภาษี", pageWidth / 2, 28, { align: "center" });

  // SUMMARY CARD

  const startY = 40;

  doc.setDrawColor(200);
  doc.roundedRect(20, startY, pageWidth - 40, 70, 3, 3);

  const line = (label, value, y) => {

    doc.setFontSize(16);

    doc.text(label, 30, y);

    doc.text(value, pageWidth - 30, y, {
      align: "right",
    });

  };

  line("รายได้รวมทั้งหมด", `${formatCurrency(summary.totalIncome)} บาท`, startY + 15);

  line("หักค่าใช้จ่ายเหมา", `- ${formatCurrency(summary.taxExpense)} บาท`, startY + 27);

  line("รายได้หลังหักค่าใช้จ่าย", `${formatCurrency(summary.incomeAfterExpense)} บาท`, startY + 39);

  line("ค่าลดหย่อนทั้งหมด", `- ${formatCurrency(summary.totalDeduction)} บาท`, startY + 51);

  doc.line(25, startY + 56, pageWidth - 25, startY + 56);

  doc.setFontSize(18);

  doc.text("ภาษีที่ต้องชำระ", 30, startY + 67);

  doc.text(
    `${formatCurrency(summary.taxPayable)} บาท`,
    pageWidth - 30,
    startY + 67,
    { align: "right" }
  );

  // TRANSACTION TABLE

  autoTable(doc, {

    startY: startY + 85,

    head: [["วันที่", "รายได้จาก", "จำนวนเงิน"]],

    body: transactions.map((t) => [
      new Date(t.date).toLocaleDateString("th-TH"),
      t.wallet_type || "-",
      `${formatCurrency(t.amount)} บาท`,
    ]),

    styles: {
      font: "THSarabunNew",
      fontStyle: "normal",
      fontSize: 14,
      cellPadding: 3,
    },

    headStyles: {
      font: "THSarabunNew",
      fontStyle: "normal",
      fillColor: [29, 79, 145],
      textColor: 255,
      fontSize: 15,
    },

  });

  // DEDUCTION TABLE

  autoTable(doc, {

    startY: doc.lastAutoTable.finalY + 15,

    head: [["ประเภทค่าลดหย่อน", "จำนวนเงิน"]],

    body: deductions.map((d) => [
      d.name || `Deduction ${d.id}`,
      `${formatCurrency(d.amount)} บาท`,
    ]),

    styles: {
      font: "THSarabunNew",
      fontStyle: "normal",
      fontSize: 14,
      cellPadding: 3,
    },

    headStyles: {
      font: "THSarabunNew",
      fontStyle: "normal",
      fillColor: [29, 79, 145],
      textColor: 255,
      fontSize: 15,
    },

  });

  // TAX BREAKDOWN

  const breakdown = calculateTaxBreakdown(summary.taxableIncome);

  autoTable(doc, {

    startY: doc.lastAutoTable.finalY + 20,

    head: [["ช่วงรายได้", "อัตราภาษี", "ภาษีที่ต้องจ่าย"]],

    body: breakdown,

    styles: {
      font: "THSarabunNew",
      fontStyle: "normal",
      fontSize: 14,
      cellPadding: 3,
    },

    headStyles: {
      font: "THSarabunNew",
      fontStyle: "normal",
      fillColor: [0, 150, 136],
      textColor: 255,
      fontSize: 15,
    },

  });

  // FOOTER

  const pageHeight = doc.internal.pageSize.height;

  doc.setFontSize(12);

  doc.text(
    `สร้างเอกสารเมื่อ ${new Date().toLocaleDateString("th-TH")}`,
    20,
    pageHeight - 10
  );

  doc.text(
    "Generated by TaxBuddy",
    pageWidth - 20,
    pageHeight - 10,
    { align: "right" }
  );

  doc.save("taxbuddy-tax-report.pdf");

}